const SUPABASE_URL='https://bjdzivfwjxplbufqedko.supabase.co',SUPABASE_PUBLISHABLE_KEY='sb_publishable_BwhwfQFF5pBZuzusS14XIg_Nj-QTnsL';
const client=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}),$=id=>document.getElementById(id);
const statusNames={awaiting_payment:'Nuevo · pago al retirar',confirmed:'Nuevo por preparar',preparing:'En preparación',ready_for_dispatch:'Listo para despacho',in_transit:'En ruta',delivered:'Entregado'};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const date=v=>new Date(v).toLocaleString('es-CL',{dateStyle:'short',timeStyle:'short'});
let selected=null,busy=false,timer,toastTimer;
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3200);}
function message(text=''){$('login-message').textContent=text;$('login-message').className=text?'message show error':'message';}
async function api(body){const {data,error}=await client.functions.invoke('manage-warehouse-orders',{body});if(error){let text='No pudimos completar la operación.';try{text=(await error.context?.json())?.error||text;}catch{}throw new Error(text);}if(data?.error)throw new Error(data.error);return data;}
function showLogin(){$('app-view').style.display='none';$('login-view').style.display='grid';clearInterval(timer);}
async function authorize(session){if(!session)return showLogin();const {data,error}=await client.auth.getUser();const user=data?.user;if(error||!user||!['warehouse_operator','portal_admin'].includes(user.app_metadata?.role)){if(user)await client.auth.signOut();showLogin();if(user)message('Esta cuenta no tiene acceso a Bodega y Despacho.');return;}$('operator-email').textContent=user.email;$('login-view').style.display='none';$('app-view').style.display='block';await load();clearInterval(timer);timer=setInterval(()=>load(true),30000);}
async function load(silent=false){if(!silent){$('orders-content').className='loading';$('orders-content').textContent='Cargando pedidos…';}try{const data=await api({action:'list',search:$('search').value.trim(),status:$('status-filter').value});renderStats(data.stats);renderOrders(data.orders);$('last-update').textContent=`Actualizado ${new Date().toLocaleTimeString('es-CL',{hour:'2-digit',minute:'2-digit'})}`;}catch(error){if(!silent){$('orders-content').className='empty';$('orders-content').textContent=error.message;}}}
function renderStats(s){$('stat-new').textContent=s.new;$('stat-preparing').textContent=s.preparing;$('stat-ready').textContent=s.ready;$('stat-transit').textContent=s.inTransit;$('stat-delivered').textContent=s.deliveredToday;document.title=s.new?`(${s.new}) Nuevos · PloFarma Bodega`:'PloFarma — Bodega y Despacho';}
function stateClass(o){return o.status==='awaiting_payment'||o.status==='confirmed'?'new':o.status;}
function renderOrders(orders){if(!orders.length){$('orders-content').className='empty';$('orders-content').textContent='No hay pedidos para este filtro.';return;}$('orders-content').className='order-list';$('orders-content').innerHTML=orders.map(o=>`<article class="order-row"><div><span class="order-number">${esc(o.order_number)}</span><span class="sub">${esc(date(o.created_at))}</span></div><div class="pharmacy-cell"><strong>${esc(o.pharmacy_name)}</strong><span class="sub">RUT ${esc(o.pharmacy_rut)}</span></div><div><span class="badge ${stateClass(o)}">${esc(statusNames[o.status]||o.status)}</span>${o.payment_method==='cash'&&o.payment_status==='pending'?'<div class="pay-warning">Cobrar al retirar</div>':''}</div><div class="units"><strong>${o.total_units} unidades</strong><span class="sub">${o.product_lines} productos</span></div><button class="primary" data-open="${o.id}">Abrir tarea →</button></article>`).join('');document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openDetail(Number(b.dataset.open))));}
async function openDetail(id){selected=null;$('dialog-title').textContent='Pedido';$('order-detail').textContent='Cargando hoja de preparación…';if(!$('order-dialog').open)$('order-dialog').showModal();try{const data=await api({action:'detail',orderId:id});selected=data.order;renderDetail(data.order);}catch(error){$('order-detail').textContent=error.message;}}
function nextAction(o){if(o.status==='awaiting_payment'||o.status==='confirmed')return ['prepare','Iniciar preparación'];if(o.status==='preparing')return ['ready_for_dispatch','Pedido revisado · dejar listo'];if(o.status==='ready_for_dispatch'&&o.payment_method!=='cash'&&o.payment_status==='paid')return ['dispatch','Marcar en ruta'];if((o.status==='in_transit'||(o.status==='ready_for_dispatch'&&o.payment_method==='cash'))&&o.payment_status==='paid')return ['deliver','Confirmar entrega'];return null;}
function renderDetail(o){$('dialog-title').textContent=o.order_number;const action=nextAction(o),needsChecks=o.status==='preparing',pickingComplete=['ready_for_dispatch','in_transit','delivered'].includes(o.status),cashWaiting=o.status==='ready_for_dispatch'&&o.payment_method==='cash'&&o.payment_status!=='paid';$('order-detail').innerHTML=`<div class="detail-summary"><div class="summary-card"><b>${esc(o.pharmacies?.display_name)}</b><p>RUT ${esc(o.pharmacies?.rut)}</p><p>Pedido recibido: ${esc(date(o.created_at))}</p></div><div class="summary-card"><span class="badge ${stateClass(o)}">${esc(statusNames[o.status])}</span><p>${o.payment_method==='cash'?'Efectivo · retiro':'Transferencia bancaria'}</p><p>${o.payment_status==='paid'?'✓ Pago registrado':'Pago pendiente'}</p></div></div><div class="pick-list"><div class="pick-head"><span>OK</span><span>Producto</span><span>SKU / lote</span><span>Laboratorio</span><span>Cantidad</span></div>${o.order_items.map(item=>`<label class="pick-item"><input class="pick-check" type="checkbox" ${needsChecks?'':`${pickingComplete?'checked ':''}disabled`}><span><b>${esc(item.product_name)}</b><span class="sub lot">Lote ${esc(item.lot_code)}</span></span><span class="sku">${esc(item.sku)}</span><span>${esc(item.laboratory)}</span><span class="pick-qty">×${item.quantity}</span></label>`).join('')}</div>${cashWaiting?'<p class="notice">El pedido está preparado. Antes de entregarlo, Administración debe registrar la recepción del efectivo.</p>':''}${action?`<form id="action-form" class="action-box"><h3>${esc(action[1])}</h3><p>${action[0]==='ready_for_dispatch'?'Revisa físicamente cada producto, lote y cantidad antes de continuar.':'Este movimiento quedará registrado con tu usuario y hora.'}</p><textarea id="action-note" minlength="3" maxlength="500" required placeholder="${action[0]==='dispatch'?'Transportista, guía o detalle del despacho':'Observación operativa'}"></textarea><button id="action-button" class="primary" data-operation="${action[0]}" ${needsChecks?'disabled':''}>${esc(action[1])} →</button></form>`:''}`;if(needsChecks){document.querySelectorAll('.pick-check').forEach(c=>c.addEventListener('change',()=>{$('action-button').disabled=![...document.querySelectorAll('.pick-check')].every(x=>x.checked);}));}if(action)$('action-form').addEventListener('submit',save);}
async function save(e){e.preventDefault();if(busy||!selected||!e.currentTarget.reportValidity())return;busy=true;const button=$('action-button');button.disabled=true;button.textContent='Guardando…';try{await api({action:'update',orderId:selected.id,operation:button.dataset.operation,expectedUpdatedAt:selected.updated_at,note:$('action-note').value.trim()});toast('Etapa actualizada correctamente.');await Promise.all([load(),openDetail(selected.id)]);}catch(error){toast(error.message);button.textContent='Actualiza y vuelve a intentar';}finally{busy=false;}}
$('login-form').addEventListener('submit',async e=>{e.preventDefault();message();const button=$('login-button');button.disabled=true;button.textContent='Validando…';const {data,error}=await client.auth.signInWithPassword({email:$('email').value.trim().toLowerCase(),password:$('password').value});button.disabled=false;button.textContent='Ingresar a operación →';if(error)return message('Correo o contraseña incorrectos.');await authorize(data.session);});
$('logout-button').addEventListener('click',()=>client.auth.signOut());$('refresh-button').addEventListener('click',()=>load());$('filter-form').addEventListener('submit',e=>{e.preventDefault();load();});$('status-filter').addEventListener('change',()=>load());document.querySelectorAll('[data-quick]').forEach(b=>b.addEventListener('click',()=>{$('status-filter').value=b.dataset.quick;load();}));$('dialog-close').addEventListener('click',()=>{if(!busy)$('order-dialog').close();});$('order-dialog').addEventListener('cancel',e=>{if(busy)e.preventDefault();});client.auth.onAuthStateChange((event,session)=>setTimeout(()=>event==='SIGNED_OUT'?showLogin():authorize(session),0));client.auth.getSession().then(({data})=>authorize(data.session));
