import {samples,demoPharmacies,demoContacts,demoOrders} from './demo-data.mjs';
const $=id=>document.getElementById(id),demo=document.body.dataset.presentation==='true';
const root=$('crm-view');let view='conversations';
const lists=[{name:'Farmacias Socio',tier:'socio'},{name:'Farmacias Acceso',tier:'acceso'}];
const materials=[{name:'Reposición de insumos',category:'Promoción',body:'Hola, estamos disponibles para ayudarte a preparar tu próxima reposición de insumos. Indícanos los productos y cantidades para revisar disponibilidad.'},{name:'Presentación PLO',category:'Presentación',body:'Bienvenido a PLO Farma. Nuestro equipo puede ayudarte con tus consultas, pedidos y seguimiento de compras.'}];
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n;};
function button(text,fn){const b=el('button',text);b.type='button';b.onclick=fn;return b;}
function field(label,node){const l=el('label',label);l.append(node);return l;}
function openConversation(row){navigate('conversations');const search=$('search');search.value=row.display_name;$('status').value='all';$('tier').value='all';search.dispatchEvent(new Event('input'));document.querySelector('#conversations button')?.click();}
function heading(title,description){root.append(el('h2',title),el('p',description,'crm-description'));}
function navigate(next){view=next;document.querySelectorAll('.crm-nav').forEach(b=>{const active=b.dataset.view===view;b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});if(!demo)return;$('workspace').hidden=view!=='conversations';root.hidden=view==='conversations';root.replaceChildren();if(view==='clients')clients();if(view==='lists')segments();if(view==='materials')library();}
function clients(){heading('Clientes','Directorio de farmacias y contactos. Abre una conversación para consultar su ficha de compras.');const input=el('input');input.placeholder='Buscar farmacia o contacto';input.setAttribute('aria-label','Buscar clientes');root.append(input);const grid=el('div',null,'crm-grid');root.append(grid);function render(){grid.replaceChildren();for(const row of samples.filter(r=>(r.display_name+' '+(r.pharmacies?.display_name||'')).toLowerCase().includes(input.value.toLowerCase()))){const card=el('article',null,'crm-card');const pharmacy=demoPharmacies.find(p=>p.id===row.pharmacy_id);card.append(el('span',pharmacy?'PLO '+pharmacy.tier:'Por verificar','crm-tag'),el('h3',pharmacy?.display_name||'Contacto nuevo'),el('p',row.display_name),el('p','+'+row.wa_id),el('p',pharmacy?(demoOrders[pharmacy.id]?.length||0)+' pedidos de ejemplo':'Sin farmacia vinculada'),button('Ver conversación',()=>openConversation(row)));grid.append(card);}if(!grid.children.length)grid.append(el('p','No hay clientes que coincidan.'));}input.oninput=render;render();}
function segments(){heading('Listas y segmentos','Agrupa farmacias para futuras comunicaciones. Crear una lista no envía mensajes ni acredita autorización para campañas.');const form=el('form',null,'crm-form'),name=el('input'),tier=el('select');name.required=true;name.maxLength=80;name.placeholder='Ej.: Reposición de octubre';for(const [value,label] of [['all','Todas las farmacias'],['socio','Socio'],['acceso','Acceso']])tier.add(new Option(label,value));const submit=el('button','Crear lista de prueba');form.append(field('Nombre de la lista',name),field('Segmento',tier),submit);form.onsubmit=e=>{e.preventDefault();if(!name.value.trim())return;lists.push({name:name.value.trim(),tier:tier.value});navigate('lists');};root.append(form);const grid=el('div',null,'crm-grid');for(const list of lists){const members=demoPharmacies.filter(p=>list.tier==='all'||p.tier===list.tier),card=el('article',null,'crm-card');card.append(el('span',members.length+' farmacias','crm-tag'),el('h3',list.name));const names=el('ul');members.forEach(p=>names.append(el('li',p.display_name)));card.append(names,el('p','Destinatarios de ejemplo · Envío no habilitado','crm-description'));grid.append(card);}root.append(grid);}
function library(){heading('Material comercial','Organiza textos para tu equipo. Estos ejemplos son borradores; no incluyen promociones ni precios aprobados.');const form=el('form',null,'crm-form'),name=el('input'),body=el('textarea');name.required=true;name.maxLength=100;body.required=true;body.maxLength=2000;body.rows=3;form.append(field('Título del material',name),field('Texto comercial',body),el('button','Guardar borrador de prueba'));form.onsubmit=e=>{e.preventDefault();if(!name.value.trim()||!body.value.trim())return;materials.push({name:name.value.trim(),body:body.value.trim(),category:'Borrador'});navigate('materials');};root.append(form);const grid=el('div',null,'crm-grid');for(const m of materials){const card=el('article',null,'crm-card');card.append(el('span',m.category,'crm-tag'),el('h3',m.name),el('p',m.body),button('Preparar en conversación',()=>{if($('reply-tools').hidden){$('notice').textContent='Selecciona primero una conversación para preparar el material.';navigate('conversations');return;}if($('reply').value.trim()){$('notice').textContent='Ya hay un borrador en esta conversación. Revísalo antes de preparar otro texto.';navigate('conversations');return;}navigate('conversations');$('reply').value=m.body;$('reply').dispatchEvent(new Event('input'));$('reply').focus();$('notice').textContent='Texto preparado como borrador. Revisa el destinatario y el contenido; no se envió ningún mensaje.';}));grid.append(card);}root.append(grid);}
$('rail-toggle').onclick=()=>{const collapsed=document.body.classList.toggle('rail-collapsed');$('rail-toggle').setAttribute('aria-expanded',String(!collapsed));$('rail-toggle').setAttribute('aria-label',collapsed?'Expandir menú':'Contraer menú');};
document.querySelectorAll('.crm-nav').forEach(b=>b.onclick=()=>navigate(b.dataset.view));
